In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
print(torch.__version__)

2.1.2+cu121


In [2]:
!nvidia-smi

Sun Jan 21 16:43:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.33                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   40C    P8              27W / 450W |    742MiB / 24564MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors
Creating Tensors as `torch.tensor` [link](https://pytorch.org/docs/stable/tensors.html)

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # What are the dimensions of tensor?

0

In [5]:
scalar.item() # What is the item of tensor?

7

In [6]:
# vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0][1]

tensor(2)

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [0,0,0],
                        [9,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [0, 0, 0],
         [9, 7, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3053, 0.0942, 0.7892, 0.6656],
        [0.3311, 0.4707, 0.4022, 0.5826],
        [0.7477, 0.3778, 0.3909, 0.1711]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor_second = torch.rand(1, 3, 5)
random_tensor_second

tensor([[[0.1255, 0.2346, 0.5242, 0.6898, 0.2865],
         [0.2373, 0.8793, 0.8441, 0.0443, 0.2861],
         [0.1607, 0.6513, 0.1121, 0.4877, 0.6812]]])

In [19]:
random_tensor_second.ndim

3

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R G B), height, width 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of ones
ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.arange(start=0, end=1000, step=50)

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [28]:
# Creating tensors like
torch.zeros_like(input=torch.arange(0,10))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
torch.zeros_like(input=torch.arange(0,10)).dtype

torch.int64

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16)
                               device=None, # what device is the tensor on 
                               requires_grad=False) # whether or not to track gradients on this tensor operates

In [31]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
multiplied = float_32_tensor * int_32_tensor

In [38]:
multiplied.dtype

torch.float32

In [39]:
(int_32_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Datatype: `tensor.dtype`
2. Shape: `tensor.shape`
3. Device: `tensor.device`

In [40]:
some_tensor = torch.rand(5, 5)
some_tensor

tensor([[0.2714, 0.7609, 0.9839, 0.6481, 0.2281],
        [0.5515, 0.1741, 0.1155, 0.6409, 0.2590],
        [0.2219, 0.3300, 0.4150, 0.6334, 0.9986],
        [0.1894, 0.1726, 0.8777, 0.2604, 0.9942],
        [0.0788, 0.3696, 0.6709, 0.1365, 0.6948]])

In [41]:
some_tensor.dtype

torch.float32

In [42]:
some_tensor.shape

torch.Size([5, 5])

In [43]:
some_tensor.ndim

2

In [44]:
some_tensor.device

device(type='cpu')

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [45]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [46]:
# Addition
tensor + 100

tensor([101, 102, 103])

In [48]:
# Subtraction
tensor - 1

tensor([0, 1, 2])

In [47]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [49]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor, 100)

tensor([101, 102, 103])

### Matrix multiplication
1. Element-wise multiplication
2. Matrix multiplication (dot Product)

There are two main rules that performing matrix multiplication needs to satisy:
1. The **inner dimensions**  must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [70]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [69]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.3227, 0.3096],
        [0.4839, 0.7329]])

In [73]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [54]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [71]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
tensor

tensor([1, 2, 3])

In [59]:
# Matrix multiplication by hand
(1 * 1) + (2 * 2) + (3 * 3)

14

In [62]:
%%timeit
value = 0
for i in range(len(tensor)):
    value = value + (tensor[i] * tensor[i])

14.1 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [72]:
%%timeit
torch.matmul(tensor, tensor)

863 ns ± 4.23 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### One of the most common errors in deep learning: shape errors

In [74]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [75]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [81]:
# Use transpose the switch the axes of tensor_B
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [79]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [82]:
# The matrix multiplication operation works when tensor_B is transposed (tensor_B.T)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])