In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
print(torch.__version__)

2.1.2+cu121


In [2]:
!nvidia-smi

Thu Jan 18 21:26:29 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.33                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   35C    P8              24W / 450W |    764MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors
Creating Tensors as `torch.tensor` [link](https://pytorch.org/docs/stable/tensors.html)

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim # What are the dimensions of tensor?

0

In [8]:
scalar.item() # What is the item of tensor?

7

In [9]:
# vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [24]:
# MATRIX
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [25]:
MATRIX.ndim

2

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [27]:
MATRIX[0][1]

tensor(2)

In [28]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [0,0,0],
                        [9,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [0, 0, 0],
         [9, 7, 8]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [31]:
# Create a random tensor size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5017, 0.2400, 0.5692, 0.3666],
        [0.9538, 0.3373, 0.6753, 0.3170],
        [0.1146, 0.1108, 0.9915, 0.0119]])

In [32]:
random_tensor.ndim

2

In [33]:
random_tensor_second = torch.rand(1, 3, 5)
random_tensor_second

tensor([[[0.4519, 0.0198, 0.6397, 0.4374, 0.7090],
         [0.1647, 0.7943, 0.9110, 0.4768, 0.9003],
         [0.8828, 0.8086, 0.2127, 0.1953, 0.3895]]])

In [34]:
random_tensor_second.ndim

3

In [36]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R G B), height, width 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)