In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
print(torch.__version__)

2.1.2+cu121


In [2]:
!nvidia-smi

Sat Apr  6 16:13:27 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.86                 Driver Version: 551.86         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  |   00000000:01:00.0  On |                  Off |
|  0%   37C    P8             22W /  450W |    1156MiB /  24564MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introduction to Tensors
Creating Tensors as `torch.tensor` [link](https://pytorch.org/docs/stable/tensors.html)

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # What are the dimensions of tensor?

0

In [5]:
scalar.item() # What is the item of tensor?

7

In [6]:
# vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0][1]

tensor(2)

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [0,0,0],
                        [9,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [0, 0, 0],
         [9, 7, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5026, 0.6219, 0.3484, 0.6499],
        [0.2053, 0.4385, 0.1337, 0.1890],
        [0.4933, 0.0628, 0.6018, 0.6253]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor_second = torch.rand(1, 3, 5)
random_tensor_second

tensor([[[0.6012, 0.2666, 0.0023, 0.2811, 0.2807],
         [0.6325, 0.6805, 0.2548, 0.9718, 0.4951],
         [0.6141, 0.3569, 0.0613, 0.1127, 0.4926]]])

In [19]:
random_tensor_second.ndim

3

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R G B), height, width 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of ones
ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
torch.arange(start=0, end=1000, step=50)

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [27]:
# Creating tensors like
torch.zeros_like(input=torch.arange(0,10))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
torch.zeros_like(input=torch.arange(0,10)).dtype

torch.int64

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16)
                               device=None, # what device is the tensor on 
                               requires_grad=False) # whether or not to track gradients on this tensor operates

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
multiplied = float_32_tensor * int_32_tensor

In [34]:
multiplied.dtype

torch.float32

In [35]:
(int_32_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Datatype: `tensor.dtype`
2. Shape: `tensor.shape`
3. Device: `tensor.device`

In [36]:
some_tensor = torch.rand(5, 5)
some_tensor

tensor([[0.9863, 0.8968, 0.1374, 0.7680, 0.3478],
        [0.0332, 0.5612, 0.3729, 0.1057, 0.4982],
        [0.0434, 0.1359, 0.8452, 0.1377, 0.3532],
        [0.2749, 0.4675, 0.9795, 0.9663, 0.2837],
        [0.3862, 0.0634, 0.5181, 0.3165, 0.7185]])

In [37]:
some_tensor.dtype

torch.float32

In [38]:
some_tensor.shape

torch.Size([5, 5])

In [39]:
some_tensor.ndim

2

In [40]:
some_tensor.device

device(type='cpu')

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [41]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [42]:
# Addition
tensor + 100

tensor([101, 102, 103])

In [43]:
# Subtraction
tensor - 1

tensor([0, 1, 2])

In [44]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [45]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor, 100)

tensor([101, 102, 103])

### Matrix multiplication
1. Element-wise multiplication
2. Matrix multiplication (dot Product)

There are two main rules that performing matrix multiplication needs to satisy:
1. The **inner dimensions**  must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [47]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.9801, 0.9100],
        [0.4597, 0.4936]])

In [48]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [49]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [51]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
# Matrix multiplication by hand
(1 * 1) + (2 * 2) + (3 * 3)

14

In [54]:
%%timeit
value = 0
for i in range(len(tensor)):
    value = value + (tensor[i] * tensor[i])

16 µs ± 76.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%%timeit
torch.matmul(tensor, tensor)

863 ns ± 4.23 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### One of the most common errors in deep learning: shape errors

In [55]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [57]:
# Use transpose the switch the axes of tensor_B
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [58]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [59]:
# The matrix multiplication operation works when tensor_B is transposed (tensor_B.T)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

#### Finding the min, max, mean, sum, etc (tensor aggregation)

In [60]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [64]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [66]:
torch.mean(x, dtype=torch.float16) # torch.mean() function  requires of float datatype?

tensor(45., dtype=torch.float16)

In [67]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max of a tensor

In [70]:
# Find the index of minimum
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [71]:
x[0]

tensor(0)

In [72]:
# Find the index of maximum
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [73]:
x[9]

tensor(90)

#### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or next to each other (hstack) depending on `dim` parameter
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [74]:
# Let's create a tensor
x = torch.arange(1, 10, dtype=torch.float16)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 torch.Size([9]))

In [77]:
# Add an extra dimension - has to be compatible with the size
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]], dtype=torch.float16),
 torch.Size([9, 1]))

In [80]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 torch.Size([1, 9]))

In [81]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16))

In [86]:
# Stack tensors on top of each other
x_vstacked = torch.stack((x, x, x, x), dim=0)
x_vstacked, x_vstacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 torch.Size([4, 9]))

In [87]:
x_hstacked = torch.stack((x, x, x, x), dim=1)
x_hstacked, x_hstacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]], dtype=torch.float16),
 torch.Size([9, 4]))

In [89]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]], dtype=torch.float16),
 torch.Size([9, 1]))

In [92]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 torch.Size([9]))

In [94]:
# torch.unsqueeze() - adds single dimensions to a target tensor at a speficic dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 torch.Size([1, 9]))

In [95]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]], dtype=torch.float16),
 torch.Size([9, 1]))

In [97]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
x_original.shape

torch.Size([224, 224, 3])

In [99]:
x_permuted = x_original.permute(dims = (2, 0, 1)) # Shifts axis 0 -> 1, 1 -> 2, 2 -> 0
x_permuted.shape

torch.Size([3, 224, 224])

#### Indexing (selecting data from tensors)

In [100]:
# Let's create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [101]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [103]:
x[0][1]

tensor([4, 5, 6])

In [105]:
x[0][1][2]

tensor(6)

In [106]:
x[:, 0]

tensor([[1, 2, 3]])

In [108]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [110]:
x[:, 1, :]

tensor([[4, 5, 6]])

In [114]:
x[:, 2, 2]

tensor([9])